-- Seed for the English Tenses module. Run after 0005_add_grammar_module.sql.
insert into public.grammar_lessons
(id, name, name_vi, category, level, summary, formula, uses, signals, examples, common_mistakes, compare_with, vocabulary)
values
('present-simple','Present Simple','Thì hiện tại đơn','Present','A1-A2','Thói quen, sự thật và lịch trình cố định.','{"affirmative":"S + V(s/es)","negative":"S + do/does not + V","question":"Do/Does + S + V?","whQuestion":"Wh-word + do/does + S + V?"}',array['Thói quen hoặc việc lặp lại.','Sự thật và trạng thái.','Lịch trình cố định.'],array['always','usually','often','every day','sometimes','never'],'[{"english":"I go to school by bike every day.","vietnamese":"Tôi đi học bằng xe đạp mỗi ngày."},{"english":"She goes to school every day.","vietnamese":"Cô ấy đi học mỗi ngày."}]','[{"wrong":"She go to school.","correct":"She goes to school.","reason":"He, She, It cần động từ thêm s hoặc es."}]','Present Simple nói thói quen; Present Continuous nói việc đang xảy ra lúc nói.','[{"english":"go to school","vietnamese":"đi học","example":"I go to school by bike."},{"english":"do homework","vietnamese":"làm bài tập","example":"I do my homework after dinner."}]'),
('present-continuous','Present Continuous','Thì hiện tại tiếp diễn','Present','A2','Việc đang xảy ra hoặc kế hoạch gần trong tương lai.','{"affirmative":"S + am/is/are + V-ing","negative":"S + am/is/are not + V-ing","question":"Am/Is/Are + S + V-ing?","whQuestion":"Wh-word + am/is/are + S + V-ing?"}',array['Đang xảy ra lúc nói.','Tình huống tạm thời.','Kế hoạch gần đã sắp xếp.'],array['now','right now','at the moment','today','this week'],'[{"english":"I am studying English now.","vietnamese":"Tôi đang học tiếng Anh bây giờ."},{"english":"We are meeting our friends tonight.","vietnamese":"Tối nay chúng tôi sẽ gặp bạn."}]','[{"wrong":"I studying English now.","correct":"I am studying English now.","reason":"Cần có am, is hoặc are trước V-ing."}]','Present Simple nói thói quen; Present Continuous nói việc đang diễn ra.','[{"english":"study English","vietnamese":"học tiếng Anh","example":"I am studying English now."}]'),
('present-perfect','Present Perfect','Thì hiện tại hoàn thành','Present','B1','Kinh nghiệm, kết quả hoặc việc bắt đầu trong quá khứ còn liên quan hiện tại.','{"affirmative":"S + have/has + V3","negative":"S + have/has not + V3","question":"Have/Has + S + V3?","whQuestion":"Wh-word + have/has + S + V3?"}',array['Kinh nghiệm.','Việc vừa hoàn thành.','Việc kéo dài đến hiện tại.'],array['already','just','yet','ever','never','since','for','recently'],'[{"english":"I have finished my homework.","vietnamese":"Tôi đã làm xong bài tập."},{"english":"She has lived here since 2020.","vietnamese":"Cô ấy đã sống ở đây từ năm 2020."}]','[{"wrong":"I have went there.","correct":"I have gone there.","reason":"Sau have hoặc has phải dùng V3."}]','Past Simple nhấn thời điểm đã kết thúc; Present Perfect nhấn liên hệ với hiện tại.','[{"english":"have experience","vietnamese":"có kinh nghiệm","example":"I have had this experience before."}]'),
('present-perfect-continuous','Present Perfect Continuous','Thì hiện tại hoàn thành tiếp diễn','Present','B2','Nhấn mạnh quá trình và thời lượng kéo dài đến hiện tại.','{"affirmative":"S + have/has been + V-ing","negative":"S + have/has not been + V-ing","question":"Have/Has + S + been + V-ing?","whQuestion":"How long + have/has + S + been + V-ing?"}',array['Nhấn mạnh thời lượng.','Hoạt động kéo dài và có dấu hiệu hiện tại.'],array['for','since','all day','recently','lately','how long'],'[{"english":"I have been studying for two hours.","vietnamese":"Tôi đã học được hai tiếng."}]','[{"wrong":"I have studying for two hours.","correct":"I have been studying for two hours.","reason":"Cấu trúc là have hoặc has been cộng V-ing."}]','Present Perfect nhấn kết quả; dạng Continuous nhấn quá trình.','[{"english":"practice regularly","vietnamese":"luyện tập thường xuyên","example":"He has been practising regularly."}]'),
('past-simple','Past Simple','Thì quá khứ đơn','Past','A2','Hành động đã xảy ra và kết thúc trong quá khứ.','{"affirmative":"S + V2/ed","negative":"S + did not + V","question":"Did + S + V?","whQuestion":"Wh-word + did + S + V?"}',array['Hành động đã kết thúc.','Chuỗi sự kiện quá khứ.'],array['yesterday','last week','ago','in 2020','when I was young'],'[{"english":"I went to school yesterday.","vietnamese":"Hôm qua tôi đã đi học."},{"english":"We watched a film last night.","vietnamese":"Tối qua chúng tôi đã xem phim."}]','[{"wrong":"I did not went.","correct":"I did not go.","reason":"Sau did hoặc did not dùng động từ nguyên mẫu."}]','Past Simple kể sự kiện đã kết thúc; Past Continuous tạo bối cảnh.','[{"english":"watch a film","vietnamese":"xem phim","example":"We watched a film last night."}]'),
('past-continuous','Past Continuous','Thì quá khứ tiếp diễn','Past','B1','Việc đang diễn ra tại một thời điểm quá khứ hoặc bị xen vào.','{"affirmative":"S + was/were + V-ing","negative":"S + was/were not + V-ing","question":"Was/Were + S + V-ing?","whQuestion":"What + was/were + S + V-ing?"}',array['Đang diễn ra tại một thời điểm quá khứ.','Hành động dài bị xen vào.'],array['at 8 p.m. yesterday','while','when','at that time'],'[{"english":"I was studying when you called.","vietnamese":"Tôi đang học thì bạn gọi."}]','[{"wrong":"I studied when you called.","correct":"I was studying when you called.","reason":"Hành động đang diễn ra dùng was hoặc were cộng V-ing."}]','Past Simple kể sự kiện; Past Continuous mô tả hành động đang diễn ra.','[{"english":"play football","vietnamese":"chơi bóng đá","example":"They were playing football."}]'),
('past-perfect','Past Perfect','Thì quá khứ hoàn thành','Past','B2','Hành động xảy ra trước một hành động khác trong quá khứ.','{"affirmative":"S + had + V3","negative":"S + had not + V3","question":"Had + S + V3?","whQuestion":"What had + S + V3?"}',array['Làm rõ hành động xảy ra trước.','Nguyên nhân trước một kết quả quá khứ.'],array['before','after','by the time','already','when'],'[{"english":"The train had left when we arrived.","vietnamese":"Tàu đã rời đi khi chúng tôi đến."}]','[{"wrong":"When I arrived, the train left.","correct":"When I arrived, the train had left.","reason":"Tàu rời đi trước nên dùng Past Perfect."}]','Past Perfect làm rõ thứ tự giữa hai sự kiện quá khứ.','[{"english":"arrive at the station","vietnamese":"đến nhà ga","example":"We arrived at the station late."}]'),
('past-perfect-continuous','Past Perfect Continuous','Thì quá khứ hoàn thành tiếp diễn','Past','C1','Nhấn mạnh thời lượng hoạt động trước một mốc quá khứ.','{"affirmative":"S + had been + V-ing","negative":"S + had not been + V-ing","question":"Had + S + been + V-ing?","whQuestion":"How long had + S + been + V-ing?"}',array['Hoạt động kéo dài trước sự kiện quá khứ.','Giải thích nguyên nhân của trạng thái quá khứ.'],array['for','since','before','until then','all day'],'[{"english":"She had been studying for hours before the exam.","vietnamese":"Cô ấy đã học hàng giờ trước kỳ thi."}]','[{"wrong":"She had studying for hours.","correct":"She had been studying for hours.","reason":"Cần had been cộng V-ing để nhấn mạnh quá trình."}]','Past Perfect nhấn kết quả; dạng Continuous nhấn thời lượng.','[{"english":"prepare for an exam","vietnamese":"chuẩn bị cho kỳ thi","example":"She had been preparing for the exam."}]'),
('future-simple','Future Simple','Thì tương lai đơn','Future','A2','Quyết định nhanh, dự đoán và lời hứa trong tương lai.','{"affirmative":"S + will + V","negative":"S + will not + V","question":"Will + S + V?","whQuestion":"Wh-word + will + S + V?"}',array['Quyết định tại thời điểm nói.','Dự đoán.','Lời hứa hoặc đề nghị.'],array['tomorrow','next week','soon','I think','probably'],'[{"english":"I will call you tonight.","vietnamese":"Tối nay tôi sẽ gọi cho bạn."}]','[{"wrong":"I will to call you.","correct":"I will call you.","reason":"Sau will dùng động từ nguyên mẫu không có to."}]','Will thường dùng cho quyết định nhanh, lời hứa hoặc dự đoán.','[{"english":"call someone","vietnamese":"gọi cho ai","example":"I will call you later."}]'),
('future-continuous','Future Continuous','Thì tương lai tiếp diễn','Future','B2','Việc sẽ đang diễn ra tại một thời điểm tương lai.','{"affirmative":"S + will be + V-ing","negative":"S + will not be + V-ing","question":"Will + S + be + V-ing?","whQuestion":"What will + S + be + V-ing?"}',array['Đang diễn ra tại một thời điểm tương lai.','Hỏi lịch sự về kế hoạch.'],array['this time tomorrow','at 8 p.m. tomorrow','next week at this time'],'[{"english":"This time tomorrow, I will be flying to London.","vietnamese":"Giờ này ngày mai tôi sẽ đang bay đến London."}]','[{"wrong":"I will studying tomorrow.","correct":"I will be studying tomorrow.","reason":"Cấu trúc là will be cộng V-ing."}]','Future Simple nói việc sẽ xảy ra; Future Continuous nhấn quá trình đang diễn ra.','[{"english":"fly to a city","vietnamese":"bay đến một thành phố","example":"I will be flying to London."}]'),
('future-perfect','Future Perfect','Thì tương lai hoàn thành','Future','B2','Việc sẽ hoàn thành trước một thời điểm tương lai.','{"affirmative":"S + will have + V3","negative":"S + will not have + V3","question":"Will + S + have + V3?","whQuestion":"When will + S + have + V3?"}',array['Hoàn thành trước một mốc tương lai.','Dự đoán một việc sẽ xong.'],array['by tomorrow','by next year','by the time','before'],'[{"english":"By Friday, I will have finished the project.","vietnamese":"Đến thứ Sáu, tôi sẽ hoàn thành dự án."}]','[{"wrong":"I will have finish the project.","correct":"I will have finished the project.","reason":"Sau have cần dùng V3."}]','Future Perfect nhấn kết quả hoàn thành trước mốc tương lai.','[{"english":"finish a project","vietnamese":"hoàn thành dự án","example":"I will have finished the project."}]'),
('future-perfect-continuous','Future Perfect Continuous','Thì tương lai hoàn thành tiếp diễn','Future','C1','Nhấn mạnh thời lượng hoạt động kéo dài đến một mốc tương lai.','{"affirmative":"S + will have been + V-ing","negative":"S + will not have been + V-ing","question":"Will + S + have been + V-ing?","whQuestion":"How long will + S + have been + V-ing?"}',array['Nhấn mạnh khoảng thời gian kéo dài đến mốc tương lai.','Mô tả quá trình dài hạn.'],array['for ... by','by next month','by the end of the year'],'[{"english":"By next year, I will have been studying English for five years.","vietnamese":"Đến năm sau, tôi sẽ học tiếng Anh được năm năm."}]','[{"wrong":"I will have studying for five years.","correct":"I will have been studying for five years.","reason":"Cấu trúc đầy đủ là will have been cộng V-ing."}]','Future Perfect nói kết quả; dạng Continuous nói thời lượng quá trình.','[{"english":"study consistently","vietnamese":"học đều đặn","example":"I will have been studying consistently."}]')
on conflict (id) do update set name = excluded.name, name_vi = excluded.name_vi, category = excluded.category, level = excluded.level, summary = excluded.summary, formula = excluded.formula, uses = excluded.uses, signals = excluded.signals, examples = excluded.examples, common_mistakes = excluded.common_mistakes, compare_with = excluded.compare_with, vocabulary = excluded.vocabulary, updated_at = now();

insert into public.grammar_writing_exercises (id, lesson_id, level, topic, vietnamese, accepted_answers, explanation, sort_order)
values
('ps-001','present-simple',1,'Daily Life','Tôi đi học mỗi ngày.',array['I go to school every day.','I go to school daily.'],'Đây là thói quen nên dùng Present Simple. Với chủ ngữ I, dùng go nguyên mẫu.',0),
('pc-001','present-continuous',1,'Study','Tôi đang học tiếng Anh bây giờ.',array['I am studying English now.','I am studying English right now.'],'Now báo hiệu hành động đang xảy ra, dùng am + studying.',0),
('pp-001','present-perfect',2,'Study','Tôi đã hoàn thành bài tập của mình.',array['I have finished my homework.','I have completed my homework.'],'Hành động đã hoàn thành và còn liên quan hiện tại, dùng have + V3.',0),
('ppc-001','present-perfect-continuous',3,'Study','Tôi đã học tiếng Anh được ba năm.',array['I have been studying English for three years.','I have studied English for three years.'],'For + khoảng thời gian và nhấn mạnh quá trình nên dùng have been studying.',0),
('pas-001','past-simple',1,'Daily Life','Hôm qua tôi đã đi học.',array['I went to school yesterday.'],'Yesterday là dấu hiệu Past Simple; go có dạng quá khứ là went.',0),
('pasc-001','past-continuous',2,'Technology','Tôi đang dùng điện thoại khi mẹ gọi.',array['I was using my phone when my mother called.','I was using my phone when my mom called.'],'Hành động dài dùng Past Continuous; sự kiện xen vào dùng Past Simple.',0),
('pap-001','past-perfect',3,'Travel','Tàu đã rời đi trước khi chúng tôi đến.',array['The train had left before we arrived.','The train had left when we arrived.'],'Hành động rời đi xảy ra trước hành động đến, dùng had + V3.',0),
('papc-001','past-perfect-continuous',4,'Study','Cô ấy đã học nhiều giờ trước khi làm bài kiểm tra.',array['She had been studying for hours before taking the test.','She had been studying for hours before the test.'],'For hours nhấn mạnh thời lượng trước một mốc quá khứ.',0),
('fs-001','future-simple',1,'Friends','Tôi sẽ gọi cho bạn tối nay.',array['I will call you tonight.', 'I''ll call you tonight.'],'Will + động từ nguyên mẫu dùng cho lời hứa hoặc quyết định về tương lai.',0),
('fc-001','future-continuous',3,'Travel','Giờ này ngày mai tôi sẽ đang đi du lịch.',array['This time tomorrow, I will be travelling.','This time tomorrow, I will be traveling.'],'This time tomorrow cho biết hành động đang diễn ra tại thời điểm tương lai.',0),
('fp-001','future-perfect',4,'Work','Đến thứ Sáu, tôi sẽ hoàn thành báo cáo.',array['By Friday, I will have finished the report.','I will have finished the report by Friday.'],'By + mốc tương lai cho biết hành động sẽ hoàn thành trước mốc đó.',0),
('fpc-001','future-perfect-continuous',5,'Education','Đến năm sau, tôi sẽ học tiếng Anh được năm năm.',array['By next year, I will have been studying English for five years.'],'For five years nhấn mạnh thời lượng kéo dài đến một mốc tương lai.',0)
on conflict (id) do update set level = excluded.level, topic = excluded.topic, vietnamese = excluded.vietnamese, accepted_answers = excluded.accepted_answers, explanation = excluded.explanation, sort_order = excluded.sort_order;
