-- IELTS Vocabulary Batch 1: Band 1.0-2.0
-- Run after 0004_add_ielts_vocabulary_metadata.sql.

do $$
declare set_id uuid;
begin
  insert into public.vocabulary_sets (owner_id, title, description, difficulty, is_public, cover_color)
  values (null, 'IELTS Band 1-2: Daily Life', 'Batch 1 - từ vựng nền tảng về sinh hoạt hằng ngày.', 'easy', true, 'blue')
  on conflict do nothing returning id into set_id;
  if set_id is null then select id into set_id from public.vocabulary_sets where title = 'IELTS Band 1-2: Daily Life'; end if;
  insert into public.vocabularies (set_id, word, meaning, english_definition, part_of_speech, pronunciation, example, example_translation, ielts_band, ielts_topic, cefr_level, ielts_use, ielts_skills, collocations, synonyms, antonyms, word_family, usage_notes) values (set_id,'routine','thói quen hằng ngày','the usual way of doing things','noun','/ruːˈtiːn/','My morning routine starts at six.','Thói quen buổi sáng của tôi bắt đầu lúc sáu giờ.',1.0,'Daily Life','A1','Useful for describing everyday life in Speaking Part 1.',array['Speaking'],array['daily routine','morning routine','busy routine'],array['habit'],array[]::text[],array['routinely'],'Use routine for a repeated pattern, not one single action.') on conflict do nothing;
  insert into public.vocabularies (set_id, word, meaning, english_definition, part_of_speech, pronunciation, example, example_translation, ielts_band, ielts_topic, cefr_level, ielts_use, ielts_skills, collocations, synonyms, antonyms, word_family, usage_notes) values (set_id,'wake up','thức dậy','to stop sleeping','phrasal verb','/weɪk ʌp/','I wake up early on weekdays.','Tôi thức dậy sớm vào các ngày trong tuần.',1.0,'Daily Life','A1','Useful for basic daily-routine answers.',array['Speaking','Listening'],array['wake up early','wake up at seven'],array['get up'],array[]::text[],array['waking'],'Wake up means stop sleeping; get up means leave the bed.') on conflict do nothing;
  insert into public.vocabularies (set_id, word, meaning, english_definition, part_of_speech, pronunciation, example, example_translation, ielts_band, ielts_topic, cefr_level, ielts_use, ielts_skills, collocations, synonyms, antonyms, word_family, usage_notes) values (set_id,'usually','thường thường','in most cases or on most occasions','adverb','/ˈjuːʒuəli/','I usually walk to school.','Tôi thường đi bộ đến trường.',1.0,'Daily Life','A1','Useful for describing frequency in Speaking Part 1.',array['Speaking'],array['usually do','usually go','usually have'],array['normally','generally'],array['rarely','never'],array['usual','usually'],'Place usually before the main verb.') on conflict do nothing;
  insert into public.vocabularies (set_id, word, meaning, english_definition, part_of_speech, pronunciation, example, example_translation, ielts_band, ielts_topic, cefr_level, ielts_use, ielts_skills, collocations, synonyms, antonyms, word_family, usage_notes) values (set_id,'weekend','cuối tuần','Saturday and Sunday','noun','/ˌwiːkˈend/','I visit my grandparents at the weekend.','Tôi thăm ông bà vào cuối tuần.',1.0,'Daily Life','A1','Useful for routine and free-time topics.',array['Speaking'],array['at the weekend','weekend activity'],array[]::text[],array[]::text[],array['weekend'],'Use on the weekend in American English and at the weekend in British English.') on conflict do nothing;
  insert into public.vocabularies (set_id, word, meaning, english_definition, part_of_speech, pronunciation, example, example_translation, ielts_band, ielts_topic, cefr_level, ielts_use, ielts_skills, collocations, synonyms, antonyms, word_family, usage_notes) values (set_id,'busy','bận rộn','having a lot to do','adjective','/ˈbɪzi/','I am busy with my homework.','Tôi bận làm bài tập.',1.0,'Daily Life','A1','Useful for describing schedules and lifestyle.',array['Speaking'],array['busy day','busy schedule','keep busy'],array['occupied'],array['free'],array['busily','business'],'Busy with is followed by a noun or -ing form.') on conflict do nothing;
end $$;

do $$
declare set_id uuid;
begin
  insert into public.vocabulary_sets (owner_id, title, description, difficulty, is_public, cover_color)
  values (null, 'IELTS Band 1-2: Education', 'Batch 1 - từ vựng nền tảng về trường học và học tập.', 'easy', true, 'violet')
  on conflict do nothing returning id into set_id;
  if set_id is null then select id into set_id from public.vocabulary_sets where title = 'IELTS Band 1-2: Education'; end if;
  insert into public.vocabularies (set_id, word, meaning, english_definition, part_of_speech, pronunciation, example, example_translation, ielts_band, ielts_topic, cefr_level, ielts_use, ielts_skills, collocations, synonyms, antonyms, word_family, usage_notes) values (set_id,'school','trường học','a place where children study','noun','/skuːl/','My school is near my home.','Trường tôi ở gần nhà.',1.0,'Education','A1','Core word for Speaking Part 1 school questions.',array['Speaking','Listening'],array['go to school','school subject','school day'],array['educational institution'],array[]::text[],array['schooling','schoolchild'],'School can refer to the building or the institution.') on conflict do nothing;
  insert into public.vocabularies (set_id, word, meaning, english_definition, part_of_speech, pronunciation, example, example_translation, ielts_band, ielts_topic, cefr_level, ielts_use, ielts_skills, collocations, synonyms, antonyms, word_family, usage_notes) values (set_id,'teacher','giáo viên','a person who teaches','noun','/ˈtiːtʃə(r)/','My English teacher is helpful.','Giáo viên tiếng Anh của tôi rất nhiệt tình.',1.0,'Education','A1','Useful for people and education descriptions.',array['Speaking','Listening'],array['English teacher','school teacher','teacher training'],array['educator'],array[]::text[],array['teach','teaching'],'Teacher is countable: a teacher, two teachers.') on conflict do nothing;
  insert into public.vocabularies (set_id, word, meaning, english_definition, part_of_speech, pronunciation, example, example_translation, ielts_band, ielts_topic, cefr_level, ielts_use, ielts_skills, collocations, synonyms, antonyms, word_family, usage_notes) values (set_id,'class','lớp học','a group of students or a lesson','noun','/klɑːs/','Our class starts at eight.','Lớp học của chúng tôi bắt đầu lúc tám giờ.',1.0,'Education','A1','Useful for describing school routines.',array['Speaking'],array['in class','English class','classmate'],array['lesson'],array[]::text[],array['classroom','classmate'],'Class can mean a group, a lesson, or a room depending on context.') on conflict do nothing;
  insert into public.vocabularies (set_id, word, meaning, english_definition, part_of_speech, pronunciation, example, example_translation, ielts_band, ielts_topic, cefr_level, ielts_use, ielts_skills, collocations, synonyms, antonyms, word_family, usage_notes) values (set_id,'learn','học','to gain knowledge or a skill','verb','/lɜːn/','I learn English at school.','Tôi học tiếng Anh ở trường.',1.0,'Education','A1','Core verb for learning experiences.',array['Speaking','Writing'],array['learn English','learn a skill','learn from experience'],array['study','discover'],array['forget'],array['learner','learning'],'Learn is often followed by a subject or skill.') on conflict do nothing;
  insert into public.vocabularies (set_id, word, meaning, english_definition, part_of_speech, pronunciation, example, example_translation, ielts_band, ielts_topic, cefr_level, ielts_use, ielts_skills, collocations, synonyms, antonyms, word_family, usage_notes) values (set_id,'homework','bài tập về nhà','work students do at home','noun','/ˈhəʊmwɜːk/','I do my homework after dinner.','Tôi làm bài tập sau bữa tối.',1.0,'Education','A1','Useful for daily school routines.',array['Speaking'],array['do homework','finish homework','homework assignment'],array['schoolwork'],array[]::text[],array[]::text[],'Homework is uncountable in standard English.') on conflict do nothing;
end $$;

do $$
declare set_id uuid;
begin
  insert into public.vocabulary_sets (owner_id, title, description, difficulty, is_public, cover_color)
  values (null, 'IELTS Band 2: Family & Friends', 'Batch 1 - từ vựng cơ bản về gia đình và các mối quan hệ.', 'easy', true, 'pink')
  on conflict do nothing returning id into set_id;
  if set_id is null then select id into set_id from public.vocabulary_sets where title = 'IELTS Band 2: Family & Friends'; end if;
  insert into public.vocabularies (set_id, word, meaning, english_definition, part_of_speech, pronunciation, example, example_translation, ielts_band, ielts_topic, cefr_level, ielts_use, ielts_skills, collocations, synonyms, antonyms, word_family, usage_notes) values (set_id,'family','gia đình','a group of people related to each other','noun','/ˈfæməli/','I come from a small family.','Tôi xuất thân từ một gia đình nhỏ.',2.0,'Family','A1','Core topic word for Speaking Part 1.',array['Speaking','Listening'],array['close family','family member','family life'],array['household'],array[]::text[],array['familiar','family-oriented'],'Family is usually treated as singular when referring to one group.') on conflict do nothing;
  insert into public.vocabularies (set_id, word, meaning, english_definition, part_of_speech, pronunciation, example, example_translation, ielts_band, ielts_topic, cefr_level, ielts_use, ielts_skills, collocations, synonyms, antonyms, word_family, usage_notes) values (set_id,'parent','cha hoặc mẹ','a mother or father','noun','/ˈpeərənt/','My parents support my studies.','Bố mẹ ủng hộ việc học của tôi.',2.0,'Family','A1','Useful for describing family support.',array['Speaking'],array['parents and children','single parent','parental support'],array['mother or father'],array[]::text[],array['parental','parenthood'],'Parents is plural for mother and father together.') on conflict do nothing;
  insert into public.vocabularies (set_id, word, meaning, english_definition, part_of_speech, pronunciation, example, example_translation, ielts_band, ielts_topic, cefr_level, ielts_use, ielts_skills, collocations, synonyms, antonyms, word_family, usage_notes) values (set_id,'friend','bạn bè','a person you know and like','noun','/frend/','I often meet my friends at the weekend.','Tôi thường gặp bạn vào cuối tuần.',2.0,'Friends & Relationships','A1','Useful for Speaking Part 1 and Part 2 people topics.',array['Speaking','Listening'],array['close friend','make friends','old friend'],array['companion'],array['enemy'],array['friendly','friendship'],'Make friends means start a friendship.') on conflict do nothing;
  insert into public.vocabularies (set_id, word, meaning, english_definition, part_of_speech, pronunciation, example, example_translation, ielts_band, ielts_topic, cefr_level, ielts_use, ielts_skills, collocations, synonyms, antonyms, word_family, usage_notes) values (set_id,'kind','tốt bụng','caring and helpful','adjective','/kaɪnd/','My best friend is kind and patient.','Bạn thân của tôi tốt bụng và kiên nhẫn.',2.0,'Friends & Relationships','A2','Useful for describing people in Speaking Part 2.',array['Speaking'],array['kind person','kind to someone','act kindly'],array['caring','helpful'],array['unkind'],array['kindness','kindly'],'Kind to someone is the common preposition pattern.') on conflict do nothing;
  insert into public.vocabularies (set_id, word, meaning, english_definition, part_of_speech, pronunciation, example, example_translation, ielts_band, ielts_topic, cefr_level, ielts_use, ielts_skills, collocations, synonyms, antonyms, word_family, usage_notes) values (set_id,'help','giúp đỡ','to make something easier for someone','verb','/help/','My brother helps me with my homework.','Anh trai giúp tôi làm bài tập.',2.0,'Family','A1','Useful for describing support and relationships.',array['Speaking','Writing'],array['help someone with something','help each other','ask for help'],array['assist'],array['hinder'],array['helpful','helpless'],'Help can be followed by an object and with + noun.') on conflict do nothing;
end $$;
